# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a45eda8abd5cd66e46d3c208773a6035d9f56a964b69657712a80e4ec62121125fdf8fed6f67e1cd2595cc9201c9fb9787dc29733bd1b0097f162c0964c5ec25

test:
  secret_key_base: cacbb03672d9bc00d3e524fffee97d2d6f800d8b05106ffa74fc6b1ed1bd941a6b77966bb7f11c2072bdebed4f3c115680cc40e6911925c2fc2a92d4bdceaea5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
